### ISSUE TITLE
Remove Section 3 (Application Registry) altogether.

### ISSUE THREAD

**Issue by tobie** [mozilla/webapps-spec#1]
A web-based app registry handler seems like an implementation detail to me. This could very well be implemented in Java on and Android or in C/C++ elsewhere.

While I understand the needs to specify those API for third parties to be able to integrate deeply with B2G, I think it's out of scope for this proposal.

**Comment by anantn** [comment]
My primary worry is that without a standardized way to install apps, manifests are not very useful in the context of a browser. I agree that we need to be as language/environment agnostic as possible, but a web based standard is important to drive adoption of manifests.

Specifically, a success condition for me personally is to be able to install applications from any store on any browser, in _addition_ to all the other ways in which a user can acquire and install web apps.
